### ISSUE TITLE
question: protein sequences of plastic-degrading enzymes?

### ISSUE THREAD

**Issue by haowang-bioinfo** [JanZrimec/Plastic_degrading_microbiome#1]
@JanZrimec nice work!

Here's a question regarding the obtained ~30k plastic-degrading enzymes detected from ocean (11,906) and soil (18,119) in this study. Where to download the protein sequences of these enzymes?

I've gone through this repo and the associated Zenodo site, but failed in finding the sequences. Could you please point me to the right place, which probably was missed by me.

Best, Hao

**Comment by JanZrimec** [comment]
Hey Hao, thanks. Yes, since we just identified and reported the hits in the paper, the protein sequences were not submitted here, but I will send them to you via mail.
Best,
Jan

**Comment by haowang-bioinfo** [comment]
Thanks @JanZrimec,

Sequences received!

Best, Hao
